language: python
python:
#  - "2.6" # missing TestCase.MultiLineEqual
  - "2.7"
#  - "3.2" # u'' prefix not supported
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script: coverage run --source deansi ./setup.py test
install:
- pip install coveralls
after_success:
- coveralls

