language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script: coverage run --source deansi ./setup.py test
install:
- pip install coveralls
after_success:
- coveralls

