name: CI

on:
  push: # on push commits at any branch
  pull_request: # on external PR
  workflow_dispatch: # on demand

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '2.7' # Py2
          - '3.8' # oldest supported Py3
          - '3' # newest supported Py3
    name: Python ${{ matrix.python-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python 2.7
        if: matrix.python-version == '2.7'
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo ln -sf python2.7 /usr/bin/python
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python get-pip.py
          rm get-pip.py
          pip install --upgrade pip setuptools wheel

      - name: Install system dependencies
        run: |
          sudo apt update -qq

      - name: Install dependencies
        run: |
          pip install -e .

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            pytest-cov
            coveralls

      - name: Unit tests
        run: |
          pytest

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
